version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-db
    networks:
      - devops-net

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    restart: always
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    networks:
      - devops-net
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge

volumes:
  sonarqube_db_data:
  nexus_data:
