services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: firas090/devopsrepository:latest
    ports:
      - "8089:8089"
    depends_on:
      - db  # Plus de condition service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/foyer_db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    networks:
      - app-network

  frontend:
    image: firas090/devopsrepository-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend  # Plus de condition service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: