  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 10s
  
  scrape_configs:
    - job_name: 'jenkins'
      metrics_path: '/prometheus'
      static_configs:
        - targets: [ '10.255.255.254:8080' ]
          labels:
            service: 'jenkins'
      params:
        module: [ default ]
      scheme: http
      tls_config:
        insecure_skip_verify: true
  
    # Prometheus self-monitoring
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
          labels:
            service: 'prometheus'
  
  
    - job_name: 'spring-app'
      metrics_path: '/foyer/actuator/prometheus'
      static_configs:
        - targets: [ 'spring-app:8089' ]

