{
 "title": "Spring Boot Foyer - Production Dashboard",
 "tags": [ "foyer-monitoring" ],
 "time": { "from": "2025-04-16T19:54:20.538Z", "to": "2025-04-16T22:25:13.280Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Pressure Indicator",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Build Duration by Stage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(default_jenkins_builds_last_stage_duration_milliseconds_summary_sum) by (stage) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins uptime ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_uptime / 1000 / 60 / 60\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Health (Stat + Traffic Light)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"spring-app:.*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by (instance) (jvm_memory_used_bytes{area=\"heap\"}) \r\n/ sum by (instance) (jvm_memory_committed_bytes{area=\"heap\"}))",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "CPU Usage Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}